# -*- coding: utf-8 -*-
"""VBA_Menden_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXQvnc4kn5w0WmWmIS8eXuDF6yhWH0GF
"""

# ============================================================
# DATEN LADEN – DWD Würzburg
# Zeitreihen: Wind (Kenia) | Luftdruck (Jonas) | Temperatur (Clara)
# Quelle: DWD CDC Open Data Server
# Cutoff: 01.05.2026
# ============================================================

import io
import re
import zipfile
import requests
import pandas as pd
from datetime import date

# ── Konfiguration ─────────────────────────────────────────────
STATION_ID = "05705"
BASE_URL   = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/"
CUTOFF     = date(2026, 5, 1)   # Festes Stoppdatum: 01.05.2026


# ── Hilfsfunktionen ───────────────────────────────────────────
def download_zip(url: str) -> zipfile.ZipFile:
    """Lädt eine ZIP-Datei von der DWD-URL und gibt sie als ZipFile zurück."""
    print(f"  → Lade: {url}")
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return zipfile.ZipFile(io.BytesIO(r.content))


def read_zip(zf: zipfile.ZipFile) -> pd.DataFrame:
    """Liest die Datendatei (produkt_*.txt) aus einem DWD-ZIP-Archiv."""
    data_file = [f for f in zf.namelist() if f.startswith("produkt_")][0]
    with zf.open(data_file) as f:
        return pd.read_csv(f, sep=";", encoding="latin-1")


def load_raw_data(station_id: str, base_url: str, cutoff: date) -> pd.DataFrame:
    """
    Lädt und kombiniert historische und aktuelle DWD-Daten für eine Station.
    Bereinigt Spaltennamen, setzt Datumsindex, ersetzt Fehlerwerte und
    schneidet am Cutoff-Datum ab.
    """
    print(f"\n{'='*55}")
    print(f"  Station: {station_id} | Cutoff: {cutoff}")
    print(f"{'='*55}")

    # Recent herunterladen
    print("\n[1/2] Aktuelle Daten:")
    zf_recent  = download_zip(f"{base_url}recent/tageswerte_KL_{station_id}_akt.zip")
    df_recent  = read_zip(zf_recent)

    # Historical herunterladen
    print("\n[2/2] Historische Daten:")
    base_hist  = base_url + "historical/"
    r          = requests.get(base_hist, timeout=30)
    pattern    = rf"tageswerte_KL_{station_id}_\d{{8}}_\d{{8}}_hist\.zip"
    filename   = re.findall(pattern, r.text)[0]
    zf_hist    = download_zip(base_hist + filename)
    df_hist    = read_zip(zf_hist)

    # Zusammenführen
    df = pd.concat([df_hist, df_recent], ignore_index=True)

    # Bereinigen
    df.columns     = df.columns.str.strip()
    df["MESS_DATUM"] = pd.to_datetime(df["MESS_DATUM"], format="%Y%m%d")
    df             = df.set_index("MESS_DATUM").sort_index()
    df             = df.replace(-999.0, float("nan"))
    df             = df.replace(-999,   float("nan"))
    df             = df[df.index.date <= cutoff]
    df             = df[~df.index.duplicated(keep="last")]

    return df


def summarize(name: str, df: pd.DataFrame):
    """Gibt eine kurze Zusammenfassung eines DataFrames aus."""
    print(f"\n  {name}:")
    print(f"    Zeitraum:       {df.index[0].date()} bis {df.index[-1].date()}")
    print(f"    Beobachtungen:  {len(df)}")
    print(f"    Fehlende Werte: {df.isna().sum().to_dict()}")


# ── Daten laden ───────────────────────────────────────────────
df_all_raw = load_raw_data(STATION_ID, BASE_URL, CUTOFF)


# ── Drei separate Zeitreihen extrahieren ──────────────────────
# Kenia – Wind
df_wind            = df_all_raw[["FM", "FX"]].copy()
df_wind.columns    = ["windgeschwindigkeit_ms", "windspitze_ms"]
df_wind            = df_wind.dropna(how="all")

# Jonas – Luftdruck
df_druck           = df_all_raw[["PM"]].copy()
df_druck.columns   = ["luftdruck_hpa"]
df_druck           = df_druck.dropna()

# Clara – Temperatur
df_temp            = df_all_raw[["TMK", "TXK", "TNK"]].copy()
df_temp.columns    = ["temperatur_mittel_c", "temperatur_max_c", "temperatur_min_c"]
df_temp            = df_temp.dropna(how="all")


# ── Zusammenfassung ───────────────────────────────────────────
print(f"\n{'='*55}")
print("  ÜBERSICHT DER ZEITREIHEN")
print(f"{'='*55}")
summarize("Wind          (Kenia)", df_wind)
summarize("Luftdruck     (Jonas)", df_druck)
summarize("Temperatur    (Clara)", df_temp)
print(f"\n{'='*55}")
print("  Daten erfolgreich geladen ✅")
print(f"{'='*55}\n")

# SCHRITT 1: DATENBEREINIGUNG – Wind Geschwindigkeit (FM)

import pandas as pd
import numpy as np

# Nur FM aus df_wind extrahieren
wind = df_wind["windgeschwindigkeit_ms"].copy()

print("Vor der Bereinigung")
print(f"Zeitraum:          {wind.index[0].date()} bis {wind.index[-1].date()}")
print(f"Anzahl Werte:      {len(wind)}")
print(f"Fehlende Werte:    {wind.isna().sum()}")
print(f"Negative Werte:    {(wind < 0).sum()}")
print(f"Nullwerte:         {(wind == 0).sum()}")
print(f"\nErste 5 Zeilen:\n{wind.head()}")

# ── Fehlende Werte behandeln ─────────────────────────────────
# Methode: lineare Interpolation (da nur 12 fehlende Tage)
wind_clean = wind.interpolate(method="linear")

# ── Sicherstellen dass kein negativer Wert existiert ─────────
wind_clean = wind_clean.clip(lower=0)

# ── Vollständigen Datumsindex sicherstellen ──────────────────
# (falls einzelne Tage komplett fehlen)
full_index = pd.date_range(
    start=wind_clean.index[0],
    end=wind_clean.index[-1],
    freq="D"
)
wind_clean = wind_clean.reindex(full_index)
wind_clean = wind_clean.interpolate(method="linear")

print("\n Nach der Bereinigung")
print(f"Zeitraum:          {wind_clean.index[0].date()} bis {wind_clean.index[-1].date()}")
print(f"Anzahl Werte:      {len(wind_clean)}")
print(f"Fehlende Werte:    {wind_clean.isna().sum()}")
print(f"Negative Werte:    {(wind_clean < 0).sum()}")
print(f"\nErste 5 Zeilen:\n{wind_clean.head()}")

# SCHRITT 2: DESKRIPTIVE ANALYSE – Wind Geschwindigkeit (FM)

import pandas as pd
import numpy as np

# ── Grundlegende Statistiken ─────────────────────────────────
print("Deskriptive Statistiken\n")

stats = pd.DataFrame({
    "Kennzahl": [
        "Anzahl Beobachtungen",
        "Mittelwert (m/s)",
        "Median (m/s)",
        "Standardabweichung (m/s)",
        "Minimum (m/s)",
        "Maximum (m/s)",
        "25% Quantil (m/s)",
        "75% Quantil (m/s)",
        "Schiefe (Skewness)",
        "Wölbung (Kurtosis)"
    ],
    "Wert": [
        len(wind_clean),
        round(wind_clean.mean(), 4),
        round(wind_clean.median(), 4),
        round(wind_clean.std(), 4),
        round(wind_clean.min(), 4),
        round(wind_clean.max(), 4),
        round(wind_clean.quantile(0.25), 4),
        round(wind_clean.quantile(0.75), 4),
        round(wind_clean.skew(), 4),
        round(wind_clean.kurt(), 4)
    ]
})

print(stats.to_string(index=False))

# ── Analyse nach Jahrzehnt ───────────────────────────────────
print("\n Mittelwert pro Jahrzehnt \n")

wind_df = wind_clean.to_frame(name="FM")
wind_df["Jahrzehnt"] = (wind_df.index.year // 10) * 10
jahrzehnt = wind_df.groupby("Jahrzehnt")["FM"].agg(
    Mittelwert="mean",
    Std="std",
    Min="min",
    Max="max"
).round(3)

print(jahrzehnt.to_string())

# ── Analyse nach Monat ───────────────────────────────────────
print("\n Mittelwert pro Monat \n")

wind_df["Monat"] = wind_df.index.month
monate = {1:"Jan", 2:"Feb", 3:"Mär", 4:"Apr", 5:"Mai", 6:"Jun",
          7:"Jul", 8:"Aug", 9:"Sep", 10:"Okt", 11:"Nov", 12:"Dez"}

monat_stats = wind_df.groupby("Monat")["FM"].agg(
    Mittelwert="mean",
    Std="std",
    Min="min",
    Max="max"
).round(3)
monat_stats.index = monat_stats.index.map(monate)

print(monat_stats.to_string())